### ISSUE TITLE
"System.MissingMethodException" with Asp.Net Core 2.1 RC1 

### ISSUE THREAD

**Issue by darting** [cofoundry-cms/Cofoundry.Plugins.Imaging.ImageSharp#1]
Please refer to https://github.com/SixLabors/ImageSharp/issues/563

MissingMethodException: Method not found: 'System.Span`1<!!1> System.MemoryExtensions.NonPortableCast(System.Span`1<!!0>)'.
SixLabors.ImageSharp.Memory.ArrayPoolMemoryManager+Buffer<T>.get_Span()

**Comment by rchcomm** [comment]
dotnet core 2.1.1 upgrade after MissingMethodException: Method not found: 'System.Spa.......

**Comment by HeyJoel** [comment]
Hi, sorry I didn't have this repo on watch for some reason so missed this.

I'm pretty sure this issue was resolved in the latest beta of image sharp so if you upgrade to the latest Cofoundry package is should be resolved (ensure your main Cofoundry packages are up to date too).

I had similar issues in one of my sites that used images from a wide range of sources and it has since been resolved. If you are continuing to get issues do let me know.
